name: pro_eye
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.9+20

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  rxdart: ^0.26.0
  flutter_localizations:
    sdk: flutter

  flutter:
    sdk: flutter

  firebase_messaging: "^9.0.0"
  firebase_core: ^1.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  built_value: ^8.0.0
  photo_view: ^0.10.3
  built_collection: ^5.0.0
  #downloads_path_provider: ^0.1.0
  flutter_launcher_icons: ^0.9.0
  flutter_downloader: ^1.6.0-nullsafety.0
  #filesystem_picker: ^1.0.4
  flutter_neumorphic: 3.0.3
  permission_handler: ^6.1.0
  gallery_saver:
    git:
      url: git@github.com:KadaDev/gallery_saver.git
  get: ^3.25.4

  image_picker: ^0.7.2+1
  flutter_screenutil: ^5.0.0-nullsafety.9
  intl: ^0.17.0
  flutter_staggered_animations: ^1.0.0
  font_awesome_flutter: ^9.0.0-nullsafety
  cached_network_image: ^3.0.0-nullsafety
  file_picker: ^3.0.0
  url_launcher: ^6.0.2
  dio: ^4.0.0-beta4
  path_provider: ^2.0.1
  path: ^1.8.0
  easy_debounce: ^1.0.2
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_inner_drawer: ^0.5.7+2

  bdaya_repository_pattern: ^3.0.0-dev.1
  hive_flutter: ^1.0.0-nullsafety.0
  bdaya_token_auth: ^2.0.0-dev.1
  enum_to_string: ^1.0.14
  flutter_picker: ^1.1.5
  lottie: ^1.0.0
  fl_chart: ^0.20.1
  infinite_scroll_pagination: ^3.0.1
  bdaya_custom_splash:
    git:
      url: git@github.com:Bdaya-Dev/custom-splash.git
      ref: master
  bdaya_fcm_handler: ^0.1.1+6
  proeye_api:
    path: ./api

dependency_overrides:
  flutter_neumorphic:
    git:
      url: git@github.com:Bdaya-Dev/Flutter-Neumorphic.git
      ref: master_temp
dev_dependencies:
  change_app_package_name: ^0.1.2
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1
  hive_generator: ^0.8.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appIcon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Black.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo-Light.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf

flutter_intl:
  enabled: true
  class_name: S
  main_locale: ar
