name: proeye_api
version: 2.0.0+3
description: ProEye Api Package
environment:
    sdk: ">=2.11.0 <3.0.0"
dependencies:
    dio: ^4.0.0-beta4
    built_value: ^8.0.0
    built_collection: ^5.0.0
dev_dependencies:
    built_value_generator: ^8.0.0
    build_runner: ^1.7.1
    test: ^1.16.5

